name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  setup-harbor-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Harbor CLI
        uses: qcserestipy/harbor-cli-setup@v0.0.1
        with:
          version: 'latest'          # or a tag like v0.0.19, or 'main'
          build_from_source: 'false' # set to 'true' to build from source (requires Go)
