name: Setup Harbor CLI, Login to Harbor and List Projects
description: Download, verify, and install the Harbor CLI, login to Harbor, and list projects

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  setup-harbor-cli-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Harbor CLI @ latest
        uses: qcserestipy/harbor-cli-setup@v0.0.1
        with:
          version: 'latest'          # or a tag like v0.0.19, or 'main'
          build_from_source: 'false' # set to 'true' to build from source (requires Go)

      # For more information on how to use the Harbor CLI, see
      # https://github.com/goharbor/harbor-cli/blob/main/doc/cli-config/_index.md
      # Note that the Harbor CLI creates a config file at ~/.harbor/config.yaml by default, which is used to store credentials and other settings.
      - name: Login to Harbor
        env:
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          harbor-cli login ${{ secrets.HARBOR_URL }} \
                --username ${{ secrets.HARBOR_USERNAME }} \
                --password "$HARBOR_PASSWORD"

      # Note that harbor CLI commands producing a table output (like harbor-cli project list) do so by opening a tty.
      # Those are not supported in GitHub Actions, so we need to specify a different output format (like JSON) using the -o flag.
      # Yaml output is also supported (e.g. -oyaml).
      - name: Create a Harbor Project
        run: |
          harbor-cli project create MyGithubActionsProject-${{ github.run_id }} -v
